package edu.mit.ll.vizlinc.components;

import edu.mit.ll.vizlinc.model.DBManager;
import edu.mit.ll.vizlinc.model.LocationValue;
import edu.mit.ll.vizlinc.model.PersonValue;
import edu.mit.ll.vizlinc.model.ResultDocSetTableModel;
import edu.mit.ll.vizlinc.model.VLQueryListener;
import edu.mit.ll.vizlinc.utils.DBUtils;
import edu.mit.ll.vizlinc.utils.UIUtils;
import edu.mit.ll.vizlincdb.document.Document;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;

/**
 * Displays all the documents that match the query.
 */
@ConvertAsProperties(
        dtd = "-//edu.mit.ll.vizlinc.components//DocList//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "DocListTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "layoutmode", openAtStartup = true)
@ActionID(category = "Window", id = "edu.mit.ll.vizlinc.components.DocListTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DocListAction",
        preferredID = "DocListTopComponent")
@Messages(
        {
    "CTL_DocListAction=DocList",
    "CTL_DocListTopComponent=Working Set",
    "HINT_DocListTopComponent=Documents that match your query"
})
public final class DocListTopComponent extends TopComponent implements VLQueryListener
{
    //TODO: Make sure that the current list is cleared before fetching into memory a 
    //new document list.
    private final String SORT_BY_AZ = "A-Z";
    private final String SORT_BY_HITS = "Mentions";
    private final String[] SORT_BY_OPTIONS = new String[]
    {
        SORT_BY_AZ, SORT_BY_HITS
    };

    public DocListTopComponent()
    {
        if(!DBManager.getInstance().isReady())
        {
            return;
        }
        
        initComponents();
        setName(Bundle.CTL_DocListTopComponent());
        setToolTipText(Bundle.HINT_DocListTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

        //Init doc number label
        updateDocNumLabel(documentTable.getModel().getRowCount());
        //Document table:
        //Make table sortable
        TableRowSorter<ResultDocSetTableModel> sorter = new TableRowSorter(getTableModel());
        documentTable.setRowSorter(sorter);
        //Set row selection listener
        documentTable.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e)
            {
                boolean enableOpenBtn = true;
                if (documentTable.getSelectedRow() == -1)
                {
                    enableOpenBtn = false;
                }
                openBtn.setEnabled(enableOpenBtn);
            }
        });
        final VLQueryListener thisAsAListener = this;
        WindowManager.getDefault().invokeWhenUIReady(new Runnable()
        {
            @Override
            public void run()
            {
                FacetedSearchTopComponent searchWin = UIUtils.getFacetedSearchWindow();
                if (searchWin != null)
                {
                    searchWin.addQueryListener(thisAsAListener);
                }
            }
        });
    }

    private TableModel createResultDocSetTableModel()
    {
        List<Document> docs;
        try
        {
            docs = DBUtils.getAllDocuments();
            return new ResultDocSetTableModel(docs);
        } catch (SQLException e)
        {
            UIUtils.reportException(this, e);
            return null;
        }
        //DocListModel model = new DocListModel(docs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        docNumberLabel = new javax.swing.JLabel();
        openBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        documentTable = new javax.swing.JTable();

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DocListTopComponent.class, "DocListTopComponent.jButton1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(docNumberLabel, org.openide.util.NbBundle.getMessage(DocListTopComponent.class, "DocListTopComponent.docNumberLabel.text")); // NOI18N

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mit/ll/vizlinc/ui/icons/open_document.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(openBtn, org.openide.util.NbBundle.getMessage(DocListTopComponent.class, "DocListTopComponent.openBtn.text")); // NOI18N
        openBtn.setToolTipText(org.openide.util.NbBundle.getMessage(DocListTopComponent.class, "DocListTopComponent.openBtn.toolTipText")); // NOI18N
        openBtn.setEnabled(false);
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        documentTable.setModel(createResultDocSetTableModel());
        documentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        documentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openSelectedDocOnDoubleClick(evt);
            }
        });
        jScrollPane2.setViewportView(documentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(docNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docNumberLabel)
                    .addComponent(openBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openBtnActionPerformed
    {//GEN-HEADEREND:event_openBtnActionPerformed
        openBtn.setEnabled(false);
        openSelectedDocument();
    }//GEN-LAST:event_openBtnActionPerformed

    private void openSelectedDocOnDoubleClick(java.awt.event.MouseEvent evt)//GEN-FIRST:event_openSelectedDocOnDoubleClick
    {//GEN-HEADEREND:event_openSelectedDocOnDoubleClick

        if (evt.getSource() == documentTable && evt.getClickCount() == 2)
        {
            openSelectedDocument();
        }
    }//GEN-LAST:event_openSelectedDocOnDoubleClick
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel docNumberLabel;
    private javax.swing.JTable documentTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton openBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened()
    {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed()
    {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p)
    {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p)
    {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    /**
     * Sets the displayed document list to the one passed as argument
     *
     * @param resultDocList new result list
     */
    private void setDocumentList(final List<Document> resultDocList)
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                updateListAndDocLabel(resultDocList);
            }
        });
    }

    private void updateListAndDocLabel(List<Document> docs)
    {
        ResultDocSetTableModel model = getTableModel();
        try
        {
            model.setList(docs);
        } 
        catch(Exception e)
        {
            UIUtils.reportException(this, e);
            return;
        }
        //Update label to show number of documents in current list
        int listSize = docs.size();
        updateDocNumLabel(listSize);
        //Enable list
        documentTable.setEnabled(true);
        //if there is something selected in the list enable open button
        if (documentTable.getSelectedRow() != -1)
        {
            openBtn.setEnabled(true);
        }
    }

    private void updateDocNumLabel(int listSize)
    {
        DecimalFormat dF = new DecimalFormat("###,###");
        String msg = dF.format((long) listSize);
        if (listSize == 1)
        {
            msg = msg + " document";
        } else
        {
            msg = msg + " documents";
        }

        docNumberLabel.setText(msg);
    }
    
    private ResultDocSetTableModel getTableModel()
    {
        return (ResultDocSetTableModel) documentTable.getModel();

    }

    /**
     * Reflects that a query is in progress and that display will be updated
     * soon Note: this method is always called from the UI dispatch thread
     */
    @Override
    public void aboutToExecuteQuery()
    {
        try
        {
            SwingUtilities.invokeAndWait(new Runnable()
            {
                @Override
                public void run()
                {
                    docNumberLabel.setText("Please Wait...");
                    documentTable.setEnabled(false);
                }
            });
        }
        catch (Exception e)
        {
            UIUtils.reportException(this, e);
        }
    }

    @Override
    public void queryFinished(List<Document> documents, List<LocationValue> locationsInFacetTree, List<PersonValue> peopleInFacetTree)
    {
        setDocumentList(documents);
    }

    private boolean areFiltersSelected()
    {
        int numFilters = UIUtils.getQueryWindow().getFilters().size();
        return (numFilters > 0) ? true : false;
    }

    private void openSelectedDocument()
    {
        int selectedRow = documentTable.getSelectedRow();
        if (selectedRow != -1)
        {
            Document selectedDocument = getTableModel().getDocumentByRow(documentTable.convertRowIndexToModel(selectedRow));
            //Lookup doc content window
            DocViewTopComponent docWin = (DocViewTopComponent) WindowManager.getDefault().findTopComponent("DocViewTopComponent");
            docWin.setDoc(selectedDocument);
        }
    }
}